# Generated by Django 2.0.7 on 2018-10-10 08:29

from django.db import migrations, models


def data_migration(apps, schema_editor):
    Job = apps.get_model("bilbyweb", "Job")
    JobCommon = apps.get_model("bilbycommon", "JobCommon")

    jobs = Job.objects.all()

    for job in jobs:
        JobCommon.objects.create(
            id=job.id,
            hpcjob_ptr=job.hpcjob_ptr,
            user=job.user,
            name=job.name,
            description=job.description,
            extra_status=job.extra_status,
            creation_time=job.creation_time,
            last_updated=job.last_updated,
            json_representation=job.json_representation,

            cluster=job.cluster,
            job_status=job.job_status,
            job_pending_time=job.job_pending_time,
            job_submitting_time=job.job_submitting_time,
            job_submitted_time=job.job_submitted_time,
            job_queued_time= job.job_queued_time,
            job_running_time=job.job_running_time,
            job_finished_time=job.job_finished_time,
            job_details=job.job_details,
            job_parameters=job.job_parameters,
        )


class Migration(migrations.Migration):
    dependencies = [
        ('bilbyweb', '0005_auto_20190206_1311'),
        ('bilbycommon', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(data_migration),
        migrations.RenameField(model_name='job', old_name='hpcjob_ptr', new_name='jobcommon_ptr'),
        migrations.AlterField(
            model_name='job',
            name='jobcommon_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=models.deletion.CASCADE,
                                       parent_link=True, primary_key=True, serialize=False,
                                       to='bilbycommon.JobCommon'),
            preserve_default=False,
        ),
    ]
