# Generated by Django 2.0.7 on 2018-10-10 08:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bilbyweb', '0006_job_common_migration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={},
        ),
        migrations.RenameModel('job', 'bilbypejob'),
        migrations.RemoveField('bilbypejob', 'user'),
        migrations.RemoveField('bilbypejob', 'name'),
        migrations.RemoveField('bilbypejob', 'description'),
        migrations.RemoveField('bilbypejob', 'extra_status'),
        migrations.RemoveField('bilbypejob', 'creation_time'),
        migrations.RemoveField('bilbypejob', 'last_updated'),
        migrations.RemoveField('bilbypejob', 'json_representation'),
    ]
