# Generated by Django 2.1.5 on 2019-02-11 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilbyweb', '0007_modify_bilbyweb_job_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_data', to='bilbyweb.BilbyBJob'),
        ),
        migrations.AlterField(
            model_name='prior',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_prior', to='bilbyweb.BilbyBJob'),
        ),
        migrations.AlterField(
            model_name='sampler',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_sampler', to='bilbyweb.BilbyBJob'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_signal', to='bilbyweb.BilbyBJob'),
        ),
    ]
