# Generated by Django 2.1.5 on 2019-02-22 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bilbycommon', '0002_jobcommon_job_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BilbyCWJob',
            fields=[
                ('jobcommon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bilbycommon.JobCommon')),
            ],
            bases=('bilbycommon.jobcommon',),
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.CharField(choices=[('sfts', 'Real Data'), ('fakedata', 'Simulated Data')], default='sfts', max_length=55)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='g_job_data_source', to='bilbycommon.JobCommon')),
            ],
        ),
    ]
