# Generated by Django 2.1.5 on 2019-02-25 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilbycw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bilbycw.BilbyCWJob')),
            ],
        ),
        migrations.AlterField(
            model_name='datasource',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cw_job_data_source', to='bilbycommon.JobCommon'),
        ),
        migrations.AddField(
            model_name='dataparameter',
            name='data_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bilbycw.DataSource'),
        ),
    ]
