# Generated by Django 2.1.5 on 2019-03-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilbycw', '0002_auto_20190225_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataparameter',
            name='name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='data_source',
            field=models.CharField(choices=[('sfts', 'Real data'), ('fakedata', 'Simulated data')], default='sfts', max_length=55),
        ),
        migrations.AlterField(
            model_name='searchparameter',
            name='name',
            field=models.CharField(max_length=55),
        ),
    ]
