# Generated by Django 2.1.5 on 2019-02-06 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_hpc_job_controller', '0007_websockettoken_timestamp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCommon',
            fields=[
                ('hpcjob_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_hpc_job_controller.HpcJob')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('extra_status', models.CharField(choices=[('none', 'None'), ('public', 'Public')], default='none', max_length=20)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('json_representation', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_job', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('django_hpc_job_controller.hpcjob',),
        ),
        migrations.AlterUniqueTogether(
            name='jobcommon',
            unique_together={('user', 'name')},
        ),
    ]
