# Generated by Django 2.1.5 on 2019-02-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilbycommon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcommon',
            name='job_type',
            field=models.CharField(choices=[('parameter_estimation', 'Parameter Estimation'), ('continuous_wave', 'Continuous Wave')], default='parameter_estimation', max_length=20),
        ),
    ]
